config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_names => {
      :verify_authy => "/verify-token",
      :enable_authy => "/enable-two-factor",
      :verify_authy_installation => "/verify-installation",
      :authy_onetouch_status => "/onetouch-status"
  }, controllers: { sessions: 'users/sessions' }
  get "/profile", to: "home#index"
  root to: "articles#index"
  resources :articles
  match '*path', to: ->(env) { [404, {}, ['Not Found']] }, via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  devise devise :authy_authenticatable, :database_authenticatable, :registerable, :validatable, :recoverable, stretches: 13
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<div class="ml-4">
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title, class: "block text-gray-700" %>
    <%= form.text_field :title, autofocus: true, class: "w-full px-4 py-3 rounded-lg bg-gray-200 mt-2 border focus:border-blue-500 focus:bg-white focus:outline-none", required: "required" %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body, class: "block text-gray-700" %>
    <%= form.text_area :body, autofocus: true, class: "w-full px-4 py-3 rounded-lg bg-gray-200 mt-2 border focus:border-blue-500 focus:bg-white focus:outline-none", required: "required" %>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>

    <%= form.submit class: "w-full block bg-indigo-500 hover:bg-indigo-400 focus:bg-indigo-400 text-white font-semibold rounded-lg
              px-4 py-3 mt-6" %>
  </div>
<% end %>
</div>

app/views/articles/edit.html.erb
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<div class="lg:flex lg:items-center lg:justify-between">
  <div class="flex-1 min-w-0">

    <%= link_to "New Article", new_article_path, class: 'm-2 p-3 block bg-indigo-500 hover:bg-indigo-400 focus:bg-indigo-400 text-white font-semibold rounded-lg' %>

    <table class='mx-auto max-w-4xl w-full whitespace-nowrap rounded-lg bg-white divide-y divide-gray-300 overflow-hidden'>
      <thead class="bg-gray-50">
      <tr class="text-gray-600 text-left">
        <th class="font-semibold text-sm uppercase px-6 py-4">
          Title
        </th>
        <th class="font-semibold text-sm uppercase px-6 py-4">
          Body
        </th>

        <th class="font-semibold text-sm uppercase px-6 py-4">

        </th>
      </tr>
      </thead>
      <tbody class="divide-y divide-gray-200">
      <% @articles.each do |article| %>
      <tr>
        <td class="px-6 py-4">
          <div class="flex items-center space-x-3">
            <%= link_to article.title, article %>
          </div>
        </td>
        <td class="px-6 py-4">
          <div class="flex items-center space-x-3">
            <%= link_to article.body, article %>
          </div>
        </td>
      </tr>
        <% end %>
      </tbody>
    </table>


  </div>

</div>

app/views/articles/new.html.erb
<div class="pl-4">
  <%= render "form", article: @article %>
</div>

app/views/articles/show.html.erb
<table class='mx-auto max-w-4xl w-full whitespace-nowrap rounded-lg bg-white divide-y divide-gray-300 overflow-hidden'>
  <thead class="bg-gray-50">
  <tr class="text-gray-600 text-left">
    <th class="font-semibold text-sm uppercase px-6 py-4">
      Title
    </th>
    <th class="font-semibold text-sm uppercase px-6 py-4">
      Body
    </th>

    <th class="font-semibold text-sm uppercase px-6 py-4">

    </th>
  </tr>
  </thead>
  <tbody class="divide-y divide-gray-200">
    <tr>
      <td class="px-6 py-4">
        <div class="flex items-center space-x-3">
          <%=  @article.title %>
        </div>
      </td>
      <td class="px-6 py-4">
        <div class="flex items-center space-x-3">
          <%=  @article.body %>
        </div>
      </td>
    </tr>
  </tbody>
</table>



<ul>
  <li><%= link_to "Edit", edit_article_path(@article), class: 'm-2 p-3 block bg-indigo-500 hover:bg-indigo-400 focus:bg-indigo-400 text-white font-semibold rounded-lg' %></li>
  <li><%= link_to "Destroy", article_path(@article),
                  class: 'm-2 p-3 block bg-red-500 hover:bg-red-400 focus:bg-red-400 text-white font-semibold rounded-lg',
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

app/views/home/index.html.erb
<h1>Settings</h1>
<br/>
<section>
<% if !current_user.authy_enabled? %>>
  <%= link_to "Add Two Factor?", user_enable_authy_path  %>
<% else %>
    <p>2FA has been enabled for this account.</p>
<% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%=javascript_include_tag "https://www.authy.com/form.authy.min.js" %>
    <%=stylesheet_link_tag "https://www.authy.com/form.authy.min.css" %>

  <div class="w-full h-screen">
    <%- if controller_name != 'sessions' && controller_name != 'registrations' && controller_name != 'devise_authy'%>
    <header class="bg-teal-400 flex">
      <nav class="flex justify-between w-full bg-purple-500 text-white p-4">
        <a href="/"><span class="font-semibold text-xl tracking-tight">Blog</span></a>
        <div class="md:items-center md:w-auto flex">
          <div class="flex text-sm" v-else>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'p-3 block bg-indigo-500 hover:bg-indigo-400 focus:bg-indigo-400 text-white font-semibold rounded-lg'  %>
          </div>
        </div>
      </nav>
    </header>
    <%- end %>
    <main>
      <%= yield %>
    </main>
  </div>
 </html>